# Generated by Django 4.2.23 on 2025-08-13 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=datetime.time(12, 0), editable=False),
            preserve_default=False,
        ),
    ]
